### ISSUE TITLE
Feature Request : Authenticate User

### ISSUE THREAD

**Issue by mms-gianni** [chriskinsman/github-action-dashboard#11]
We need to authenticate users to make the dashboard more private. Specially when running on Heroku. 

I am considering to build something with https://www.passportjs.org/ as described here : 
https://blog.jscrambler.com/vue-js-authentication-system-with-node-js-backend

**Comment by mms-gianni** [comment]
Solved in this pullrequest #12 #

**Comment by chriskinsman** [comment]
See comments on pull request.  Thanks for all the contributions!  Sorry it took me awhile to notice they were sitting out here...
