### ISSUE TITLE
Errors on Webhook and interval check prevent updating board

### ISSUE THREAD

**Issue by zacharyfleck** [chriskinsman/github-action-dashboard#24]
Whenever a webhook is received, or the program tries to check for updates every 15 minutes, the logs indicate an error and do not update the dashboard. Restarting the docker container will update on first boot, but the issues persist.

On 15 minute update `Error getting initial data TypeError: Cannot read properties of undefined (reading 'listRepos')` and references Line 137 of actions.js: https://github.com/chriskinsman/github-action-dashboard/blob/main/actions.js#L137

On Webhook received `Error processing workflow_run received id: <workflow_id_redacted>, name: workflow_run` which is then followed by the JSON payload of the webhook, which seems to be expected behavior.

For additional info: All permissions referenced in the README.md are in place, and the app is installed at the organization level with access to all repos in the org.

**Comment by christopher-dejesus** [comment]
I'm getting the exact same error. Any idea what is happening with this?

**Comment by zacharyfleck** [comment]
@christopher-dejesus I forked the repo, wanted to start poking at it to figure it out but unfortunately haven't had much time yet. My guess is that something changed with the payload from the webhook and it's not processing it correctly. Payloads are similar on the 15 minute reload so may be the same issue. I'll try to poke at it a bit tomorrow. If I can figure it out, I'll open a PR and also update here.

**Comment by chriskinsman** [comment]
I haven't had a chance to look at this yet. Hopefully have some time this weekend!

**Comment by chriskinsman** [comment]
This should be fixed in #25 

v1.7.0 should have it all fixed up.
