### ISSUE TITLE
Support github enterprise

### ISSUE THREAD

**Issue by tim-reslv** [chriskinsman/github-action-dashboard#3]
Hi I'm trying to run github-action-dashboard for GitHub Enterprise, after test, seems it support github.com only.

Is there plan to support GitHub Enterprise?

**Comment by chriskinsman** [comment]
I don't have access to GitHub Enterprise or know how it might differ.  I would be open to accepting pull requests from someone who can test it there, etc.

**Comment by vikas027** [comment]
Hello @tim-reslv ,

Did you ever got this working? I am too [testing](https://github.com/chriskinsman/github-action-dashboard/issues/13) it in an enterprise account, will update this issue with my findings or raise a PR with the required steps to get it working.

**Comment by jgeorge300** [comment]
I've been able to get the Dashboard working with my company's ghe deployment. Just 4 changes that should be configurable.

**Comment by chriskinsman** [comment]
Could you share the changes?

**Comment by jgeorge300** [comment]
I've created a draft PR with my hard coded changes. I should be able to make them configurable following your ENV pattern.
